@host = http://localhost:3000

### Register new user
POST {{host}}/register
Content-Type: application/json

{
  "username": "test3",
  "email": "test3@email.com",
  "password": "password"
}

### Login user
# @name login
POST {{host}}/login
Content-Type: application/json

{
  "username": "ChangedTest3",
  "email": "test3@email.com",
  "password": "ChangedPassword"
}

### Get user information
@token = {{login.response.body.token}}
GET {{host}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

### Update Profile
PATCH {{host}}/update-profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "changedtest3",
  "email": "test3@email.com",
  "password": "changedPassword"
}

### Get all stickers
GET {{host}}/api/stickers/sticker
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a new sticker
POST {{host}}/api/stickers/sticker
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "content": "Type your new note here...",
  "positionX": 300,
  "positionY": 300,
  "width": 300,
  "height": 300,
  "color": "Y#FFEB3B",
  "zIndex": 585
}

### Update a sticker
PATCH {{host}}/api/stickers/sticker/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "content": "Changed note here...",
  "positionX": 300,
  "positionY": 300,
  "width": 300,
  "height": 300,
  "color": "Y#FFEB3B",
  "zIndex": 585
}

### Delete a sticker
DELETE {{host}}/api/stickers/sticker/5
Authorization: Bearer {{token}}

### Get all stickers settings
GET {{host}}/api/stickers/sticker-settings
Authorization: Bearer {{token}}
Content-Type: application/json

### Post sticker preference
POST {{host}}/api/stickers/sticker-settings
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "defaultColor": "blue",
  "defaultSizeWidth": 100,
  "defaultSizeHeight": 100
}

### Update a sticker
PATCH {{host}}/api/stickers/sticker-settings/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "defaultColor": "purple",
  "defaultSizeWidth": 150,
  "defaultSizeHeight": 150
}

### Delete a sticker setting
DELETE {{host}}/api/stickers/sticker-settings/4
Authorization: Bearer {{token}}

### Get all events on calendar
GET {{host}}/api/events/event
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a new event
POST {{host}}/api/events/event
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "eventName": "Christmas Concert",
  "eventDate": "2024-12-05T17:00:00Z",
  "description": "School Christmas Concert"
}

### Update a event
PATCH {{host}}/api/events/event/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "eventName": "3rd Grade Christmas Concert",
  "eventDate" : "2024-12-06T17:00:00Z",
  "description": "Changed date of Christmas concert"
}

### Delete a event
DELETE {{host}}/api/events/event/3
Authorization: Bearer {{token}}

### Get all to do lists
GET {{host}}/api/lists/todo
Authorization: Bearer {{token}}
Content-Type: application/json

### Post to do 
POST {{host}}/api/lists/todo
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "taskName": "Clean car",
  "isCompleted": false
}

### Update a to do
PATCH {{host}}/api/lists/todo/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 1,
  "taskName": "Clean and wash car",
  "isCompleted": false
}

### Delete a to do
DELETE {{host}}/api/lists/todo/5
Authorization: Bearer {{token}}

### Get all shopping lists
GET {{host}}/api/lists/shopping
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a shopping list
POST {{host}}/api/lists/shopping
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 5,
  "itemName": "Pink Coat",
  "quantity": 1,
  "store": "Target",
  "price": 25.75
}

### Update a shopping list
PATCH {{host}}/api/lists/shopping/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 5,
  "itemName": "Green Coat",
  "quantity": 1,
  "store": "Target",
  "price": 27.75
}

### Delete a shopping list
DELETE {{host}}/api/lists/shopping/5
Authorization: Bearer {{token}}

### Get all journals
GET {{host}}/api/journals/journal
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a journal entry
POST {{host}}/api/journals/journal
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 5,
  "entryText": "Saw a cute cat."
}

### Update a journal entry 
PATCH {{host}}/api/journals/journal/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 5,
  "entryText": "Saw 2 cute cats."
}

### Delete a journal entry
DELETE {{host}}/api/journals/journal/5
Authorization: Bearer {{token}}
