@host = http://localhost:3000

### Use token saved from general.http @token = {{token}}
@token = {{token}}

### Get all personal passwords
GET {{host}}/api/personalPasswords/password
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a personal password
POST {{host}}/api/personalPasswords/personal-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 5,
  "accountName": "Example account",
  "username": "ExampleUsername",
  "password": "ExamplePassword"
}

### Update a personal password
PATCH {{host}}/personalPasswords/personal-password/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 5,
  "accountName": "Example changed account",
  "username": "ExampleChangedUsername",
  "password": "ExampleChangedPassword",
}

### Delete a personal password
DELETE {{host}}/personalPasswords/personal-passwords/5
Authorization: Bearer {{token}}

### Get all grocery lists
GET {{host}}/personal/grocerylist
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a grocery list
POST {{host}}/personal/grocerylist
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 5,
  "itemName": "Almond Milk",
  "quantity": 2,
  "isPurchase": false,
}

### Update a grocery listt
PATCH {{host}}/personal/grocerylist/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 5,
  "itemName": "Oat Milk",
  "quantity": 2,
  "isPurchase": false,
}

### Delete a grocery list
DELETE {{host}}/personal/grocerylist/5
Authorization: Bearer {{token}}

### Get all meals for week
GET {{host}}/personal/weeklymeals
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a meal
POST {{host}}/personal/weeklymeals
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "dayOfWeek": "Monday",
  "mealDescription": "Breakfast: Granola, Lunch: Salad, Dinner: Sweet Potato Tacos"
}

### Update a meal
PATCH {{host}}/personal/weeklymeals/1
Authorization: Bearer {{token}}
Content-Type: application/json

 {
  "userId:": 3,
  "dayOfWeek": "Tuesday",
  "mealDescription": "Breakfast: Oatmeal, Lunch: Salad, Dinner: Sweet Potato Tacos"
}

### Delete a meal
DELETE {{host}}/personal/weeklymeals/5
Authorization: Bearer {{token}}

### Get all budget entries
GET {{host}}/personal/budget
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a budget entry
POST {{host}}/personal/budget
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "category": "Groceries",
  "amount": 250.75,
  "isExpense": true,
}

### Update a budget entry
PATCH {{host}}/personal/budget/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "category": "Groceries-Snacks",
  "amount": 20.75,
  "isExpense": true,
}

### Delete a budget entry
DELETE {{host}}/personal/budget/5
Authorization: Bearer {{token}}

### Get all spending entries
GET {{host}}/personal/spending
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a spending entry
POST {{host}}/personal/spending
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "description": "Vacation",
  "amount": 400,
}

### Update a spending entry
PATCH {{host}}/personal/spending/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "description": "Family Visit",
  "amount": 200,
}

### Delete a spending entry
DELETE {{host}}/personal/spending/5
Authorization: Bearer {{token}}

### Get all medical data
GET {{host}}/personal/medical
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a medical entry
POST {{host}}/personal/medical
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "medicalCondition": "Asthma",
  "prescription": "Azelaic acid",
  "doctorName": "Dr.Matthews",
}

### Update a medical entry
PATCH {{host}}/personal/medical/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "medicalCondition": "Rosacea",
  "prescription": "Eucerin lotion",
  "doctorName": "Dr.Matthews",
}

### Delete a medical entry
DELETE {{host}}/personal/medical/5
Authorization: Bearer {{token}}

### Get all habit tracker data
GET {{host}}/personal/habits
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a habit tracker entry
POST {{host}}/personal/habits
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "habitName": "Skincare",
  "frequency": "daily",
  "goal": 2,
  "progress": 3,
}

### Update a habit tracker entry
PATCH {{host}}/personal/habits/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "habitName": "Haircare",
  "frequency": "daily",
  "goal": 1,
  "progress": 3,
}

### Delete a habit tracker entry
DELETE {{host}}/personal/habits/5
Authorization: Bearer {{token}}

### Get all cleaning data
GET {{host}}/personal/cleaning
Authorization: Bearer {{token}}
Content-Type: application/json

### Post a cleaning entry
POST {{host}}/personal/cleaning
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "taskName": "Vacuum",
  "frequency": "daily",
  "isCompleted": false,
}

### Update a cleaning entry
PATCH {{host}}/personal/cleaning/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId:": 3,
  "taskName": "Dust",
  "frequency": "daily",
  "isCompleted": false,
}

### Delete a cleaning entry
DELETE {{host}}/personal/cleaning/5
Authorization: Bearer {{token}}