-- AlterTable
ALTER TABLE "MonthlyBudget" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ShoppingList" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "SpendTracker" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
